typedef int __sig_atomic_t;
typedef int __pid_t;
typedef long long __time_t;
typedef long long __syscall_slong_t;
typedef int __uid_t;
typedef long long __clock_t;
typedef unsigned char __u_char;
typedef unsigned short __u_short;
typedef unsigned int __u_int;
typedef unsigned long long __u_long;
typedef long long __quad_t;
typedef unsigned long long __u_quad_t;
typedef unsigned short __uint16_t;
typedef unsigned int __uint32_t;
typedef unsigned long long __uint64_t;
typedef unsigned long long __fsid_t;
typedef unsigned long long __loff_t;
typedef unsigned long long __ino_t;
typedef unsigned long long __ino64_t;
typedef unsigned long long __dev_t;
typedef int __gid_t;
typedef unsigned int __mode_t;
typedef unsigned int __nlink_t;
typedef unsigned long long __off_t;
typedef unsigned long long __off64_t;
typedef unsigned int __id_t;
typedef long long __ssize_t;
typedef int __daddr_t;
typedef char * __caddr_t;
typedef int __key_t;
typedef int __clockid_t;
typedef int __timer_t;
typedef unsigned int __useconds_t;
typedef int __suseconds_t;
typedef char __int8_t;
typedef short __int16_t;
typedef int __int32_t;
typedef long long __int64_t;
typedef long long __blksize_t;
typedef long long __blkcnt_t;
typedef unsigned long long __fsblkcnt_t;
typedef unsigned long long __fsfilcnt_t;
typedef long long __blkcnt64_t;
typedef unsigned long long __fsblkcnt64_t;
typedef unsigned long long __fsfilcnt64_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef unsigned long long uintptr_t;
typedef long long intptr_t;
typedef unsigned long long __CPU_MASK_TYPE;
typedef unsigned char __uint8_t;
typedef unsigned int __socklen_t;
typedef int int32_t;
typedef long long int64_t;
typedef char int_fast8_t;
typedef unsigned char uint_fast8_t;
typedef short int_fast16_t;
typedef unsigned short uint_fast16_t;
typedef int int_fast32_t;
typedef unsigned int uint_fast32_t;
typedef long long int_fast64_t;
typedef unsigned long long uint_fast64_t;
typedef long long intmax_t;
typedef unsigned long long uintmax_t;
typedef unsigned char uint8_t;
typedef long long __intptr_t;
typedef long long __intmax_t;
typedef unsigned long long __uintmax_t;
